apiVersion: apps/v1
kind: Deployment
# opis deploymentu
metadata:
  name: innovate
  namespace: develop
  # namespace: myapp
  # annotation su nepovinne udaje pouzite na popis deploymentu, ktore ale nie su pouzite ako identifikatory pri query
  annotations:
    description: My training app
    release: "1.0"
spec:
  replicas: 4
  strategy:
    # type : Recreate
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  # selector sluzi na prepojenie servicov s deploymentami
  selector:
    matchLabels:
      app: innovate

  # labels / identifying metadata that you can use to sort and select sets of api objects
  # sluzia na identifikaciu objektov v api calloch
  # kubectl get deployments --selector=app=innovate
  
  template:
    metadata:
      labels:
        app: innovate
      annotations:
        version: "1.0"
        maintainer: Mensa
    
    spec:
      containers:
      - name: innovate
        image: fsainframensaregistry.azurecr.io/monko-cicd.westeurope.azurecontainer.io/innovate:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests: 
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
        ports:
        - containerPort: 9113
        imagePullPolicy: Always
        resources:
          requests: 
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"